### ISSUE TITLE
Material error

### ISSUE THREAD

**Issue by yakuu** [yakuu/morbus#1]
> [15:00:29] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@33232427:
> java.lang.NoSuchFieldError: AIR
>     at blue.gray.init.ModBlocks.<clinit>(ModBlocks.java:17) ~[ModBlocks.class:?]
>     at blue.gray.util.handlers.RegistryHandler.onBlockRegister(RegistryHandler.java:25) ~[RegistryHandler.class:?]
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_374_RegistryHandler_onBlockRegister_Register.invoke(.dynamic) ~[?:?]
>     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
>     at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
>     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
>     at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734) [GameData.class:?]
>     at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639) [Loader.class:?]
>     at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270) [FMLClientHandler.class:?]
>     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bib.class:?]
>     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
>     at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
>     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

full log: https://pastebin.com/394S1Cta

**Comment by yakuu** [comment]
.\gradlew build

fixed the issue, exporting from eclipse did not work for me. 👍
